general:
    run_id: finetune-nequip-for-cgap20u
    progress: logged

# finetune a pre-trained NequIP model ...
model:
    +load_model_component:
        path: <insert path to model>
        key: many-body

# ... on structures from local files ...
data:
    train:
        +file_dataset:
            # take the first 1280 structures from train-cgap20u.xyz
            path: train-cgap20u.xyz
            cutoff: 3.7
            n: 1280
            shuffle: false
    valid:
        +file_dataset:
            # use all structures from val-cgap20u.xyz
            path: val-cgap20u.xyz
            cutoff: 3.7

# ... on both energy and forces ...
loss:
    - component: +PerAtomEnergyLoss()
    - component:
          +Loss: { property: forces, metric: RMSE }

# ... with the following settings ...
fitting:
    trainer_kwargs:
        max_epochs: 100
        accelerator: auto
        check_val_every_n_epoch: 2

    optimizer:
        +Optimizer:
            name: AdamW
            lr: 0.003

    scheduler:
        +LRScheduler:
            name: ReduceLROnPlateau
            factor: 0.5
            patience: 10

    loader_kwargs:
        batch_size: 64

# ... and log to Weights & Biases
wandb:
    project: graph-pes-quickstart
