# define a radial cutoff to use throughout the config
CUTOFF: 3.7  # in Å

general:
    progress: logged

# train a lightweight NequIP model ...
model:
    offset:
        # note the "+" prefix syntax: refer to the
        # data2objects package for more details
        +FixedOffset: { C: -148.314002 }
    many-body:
        +NequIP:
            elements: [C]
            cutoff: =/CUTOFF  # reference the radial cutoff defined above
            layers: 2
            features:
                channels: [16, 8, 4]
                l_max: 2
                use_odd_parity: true
            self_interaction: linear

# ... on structures from local files ...
data:
    train:
        +file_dataset:
            path: train-cgap17.xyz
            cutoff: =/CUTOFF
            n: 1280
            shuffle: false
    valid:
        +file_dataset:
            path: val-cgap17.xyz
            cutoff: =/CUTOFF
    test:
        +file_dataset:
            path: test-cgap17.xyz
            cutoff: =/CUTOFF

# ... on both energy and forces (weighted 1:1) ...
loss:
    - +PerAtomEnergyLoss()
    - +ForceRMSE()

# ... with the following settings ...
fitting:
    trainer_kwargs:
        max_epochs: 250
        accelerator: auto
        check_val_every_n_epoch: 5

    optimizer:
        +Optimizer:
            name: AdamW
            lr: 0.01

    scheduler:
        +LRScheduler:
            name: ReduceLROnPlateau
            factor: 0.5
            patience: 10

    loader_kwargs:
        batch_size: 64

# ... and log to Weights & Biases
wandb:
    project: graph-pes-quickstart
